baseurl = "http://www.analytic-kata.com/"
languageCode = "en-us"
title = "Analytic Kata"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Nick Ryberg"
	description = "Learn analysis through action - you learn by movement, develop new ways of thinking and become the master of your own data."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/nryberg/analytic-kata"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "light green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "digitalcraftsman"


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 10

[[menu.main]]
	name   = "Blog"
	url    = "blog/"
	weight = 20

[[menu.main]]
	name   = "Exercises"
	url    = "exercises/"
	weight = 30

[[menu.main]]
	name   = "Data"
	url    = "data/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
