# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://www.analytic-kata.com" # In most cases this will work.

# Site title
title = "Analytic Kata"

# Copyright
copyright = "(c) 2016 Nick Ryberg."

# Language
languageCode = "en-EN"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "reggie"

# Pagination
paginate = 10
paginatePath = "page"


[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

#[taxonomies]
#    tag = "tags"
#    topic = "topics"

[author]
    name = "Nick Ryberg"
    email = "nryberg@analytic-kata.com"

#
# All parameters below here are optional and can be mixed and matched.
#

# bootswatch theme name, unmark and select one: cerulean, cosmo, cyborg, darkly,
# default, flatly, journal,  lumen, paper, readable, sandstone, simplex,
# slate, spacelab, superhero, united, yeti.


[params]
    # You can use markdown here.
    description = "Learn analysis through action - you learn by movement, develop new ways of thinking and become the master of your own data."
    # Google Analytics.
    googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    github = "https://github.com/nryberg" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
